Changed versions 4

diff --git a/.github/workflows/packer-validate-pre-merge.yml b/.github/workflows/packer-validate-pre-merge.yml
--- a/.github/workflows/packer-validate-pre-merge.yml
+++ b/.github/workflows/packer-validate-pre-merge.yml
@@ -12,7 +12,7 @@ jobs:
       - uses: actions/checkout@v2
       
       - name: Set up Cloud SDK
-        uses: google-github-actions/setup-gcloud@main
+        uses: google-github-actions/setup-gcloud@v2
         with:
           version: 'latest'
           project_id: ${{ secrets.GCP_PROJECT_ID }}
@@ -26,6 +26,10 @@ jobs:
 
       - name: Create account.json
         run: echo "${{ secrets.GCP_SA_KEY }}" > account.json
+
+      - name: Validate account.json
+        run: |
+          cat account.json | jq . > /dev/null || (echo "Invalid JSON in account.json" && exit 1)
 
       - name: Run packer init
         run: packer init .
