Feature/assignment 04 (#14)
* Assignment 02

- Created a authentication system using Go
- Created a Github to do simple build and test check upon pushing it to main branch

* Testing out if the actions are working?

- Added a line in README

* Testing again now with postgres config

* Cool

* Made changes only in the README to check if the Git Actions are working

- README is changed.

* Found the mistake

* Missing UUID extension added in the Github Actions File

- ERROR: function uuid_generate_v4() does not exist
- I think this is causing the subsequent to be failing
- Resolution: Added a line to install the extension in YAML

* Testing Forked Repo to Organization Repo Secrets part
- Gave myself an admin access to see if my forked repo is able to access the secrets of base org repo

* pretty much trying the same thing

* Created a Packer Image for my VPC with the configuration mentioned in the assignment
- Use the new.pkr.hcl, not the template.pkr
- Wrote the basic workflow pre-merge

* Trying the workflow

* Delete Template HCL

* TEsting the workflow

* Test Workflow

* Added copying secrets to json

* Changed versions

* Changed versions 1

* Changed versions 2

* Changed versions 3

* Changed versions 4

* Changed versions 5

* Changed versions - made it to base64

* Added Post Merge

* Added Post Merge 1

diff --git a/.github/workflows/packer-build-post-merge.yml b/.github/workflows/packer-build-post-merge.yml
--- a/.github/workflows/packer-build-post-merge.yml
+++ b/.github/workflows/packer-build-post-merge.yml
@@ -1,4 +1,4 @@
-name: Build and Deploy Packer Image
+name: Build, Test, and Deploy Packer Image
 
 on:
   push:
@@ -6,7 +6,7 @@ on:
       - main
 
 jobs:
-  build-and-test:
+  build-test-and-deploy:
     runs-on: ubuntu-latest
     
     steps:
@@ -53,12 +53,6 @@ jobs:
     - name: Build Project
       run: go build -v ./...
 
-    - name: Archive application artifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: webapp
-        path: bin/webapp
-
     - name: Run Tests
       run: go test -v ./...
       env:
@@ -68,51 +62,31 @@ jobs:
         POSTGRES_HOST: localhost
         POSTGRES_PORT: 5432
 
-  build-packer-image:
-    needs: build-and-test
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
+    - name: Install required packages
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y jq
 
-      # Download the application artifact
-      - name: Download application artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: webapp
-          path: bin/
+    - name: Decode and create account.json
+      run: echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > account.json
 
-      - name: Install required packages
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y jq
+    - name: Validate account.json
+      run: |
+        cat account.json | jq . > /dev/null || (echo "Invalid JSON in account.json" && exit 1)
 
-      - name: Decode and create account.json
-        run: echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > account.json
+    - name: Install Packer
+      run: |
+        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
+        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
+        sudo apt-get update && sudo apt-get install packer
 
-      - name: Validate account.json
-        run: |
-          cat account.json | jq . > /dev/null || (echo "Invalid JSON in account.json" && exit 1)
-         
-      - name: Set up Cloud SDK
-        uses: google-github-actions/setup-gcloud@v2
-        with:
-            version: 'latest'
-            project_id: ${{ secrets.GCP_PROJECT_ID }}
-            credentials_json: ${{ secrets.GCP_SA_KEY_BASE64 }}
+    - name: Run packer init
+      run: packer init .
 
-      - name: Install Packer
-        run: |
-          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
-          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
-          sudo apt-get update && sudo apt-get install packer
-
-      - name: Run packer init
-        run: packer init .
-
-      - name: Build Packer Image
-        env:
-          GOOGLE_APPLICATION_CREDENTIALS: account.json
-        run: packer build -var 'repository_url=https://github.com/${{ github.repository }}.git' \
-                       -var 'branch=main' \
-                       -var 'project_id=${{ secrets.GCP_PROJECT_ID }}' \
-                       new.pkr.hcl
+    - name: Build Packer Image
+      env:
+        GOOGLE_APPLICATION_CREDENTIALS: account.json
+      run: packer build -var 'repository_url=https://github.com/${{ github.repository }}.git' \
+                     -var 'branch=main' \
+                     -var 'project_id=${{ secrets.GCP_PROJECT_ID }}' \
+                     new.pkr.hcl
