Trying to add Google Default

diff --git a/.github/workflows/packer-build-post-merge.yml b/.github/workflows/packer-build-post-merge.yml
--- a/.github/workflows/packer-build-post-merge.yml
+++ b/.github/workflows/packer-build-post-merge.yml
@@ -56,33 +56,36 @@ jobs:
     #     POSTGRES_HOST: localhost
     #     POSTGRES_PORT: 5432
 
-    # - name: Install required packages
-    #   run: |
-    #     sudo apt-get update
-    #     sudo apt-get install -y jq
-
-    # - name: Set up Cloud SDK
-    #   uses: google-github-actions/setup-gcloud@v0.2.0 # Updated to use a specific version; check for the latest version
-    #   with:
-    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
-    #     service_account_key: ${{ secrets.GCP_SA_KEY_2 }}
-    #     export_default_credentials: true
-
-    # - name: Install Packer
-    #   run: |
-    #     echo "${{ secrets.GCP_SA_KEY_2 }} ${{ secrets.GCP_PROJECT_ID }}"
-    #     curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
-    #     sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
-    #     sudo apt-get update && sudo apt-get install packer
-
-    # - name: Run packer init
-    #   run: packer init new.pkr.hcl
-
-    # - name: Build Packer Image
-    #   run: PACKER_LOG=1 packer build -var-file=variables.pkrvars.hcl new.pkr.hcl
-
-    - name: Checking ENV
-      env: 
-        GCP_PROJECT_ID_S: ${{ secrets.GCP_PROJECT_ID }}
+    - name: Decode and create account.json
       run: |
-        echo "${{ secrets.GCP_PROJECT_ID }}"
+        echo "${{ secrets.GCP_SA_KEY_2 }}" > account-2.json
+        echo "Decoded account.json content:"
+        cat account-2.json
+        cat account-2.json | jq . > /dev/null || (echo "Invalid JSON in account.json" && exit 1)
+
+    - name: Install required packages
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y jq
+
+    - name: Set up Cloud SDK
+      uses: google-github-actions/setup-gcloud@v0.2.0 # Updated to use a specific version; check for the latest version
+      with:
+        project_id: ${{ secrets.GCP_PROJECT_ID }}
+        service_account_key: ${{ secrets.GCP_SA_KEY_2 }}
+        export_default_credentials: true
+
+    - name: Install Packer
+      run: |
+        echo "${{ secrets.GCP_SA_KEY_2 }} ${{ secrets.GCP_PROJECT_ID }}"
+        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
+        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
+        sudo apt-get update && sudo apt-get install packer
+
+    - name: Run packer init
+      run: packer init new.pkr.hcl
+
+    - name: Build Packer Image
+      env:
+        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/account-2.json
+      run: PACKER_LOG=1 packer build -var-file=variables.pkrvars.hcl new.pkr.hcl
